--------PARTE 1:
--------1) FAZER UMA PESQUISA QUE RETORNE O CóDIGO DE ATENDIMENTO E A DATA DE ATENDIMENTO E A DATA DE ALTA.
--------TABELAS: ATENDIME.
            SELECT ATENDIME.CD_ATENDIMENTO, ATENDIME.DT_ATENDIMENTO, ATENDIME.DT_ALTA
            FROM ATENDIME

--------2) FAZER UM SELECT QUE TRAGA O CóDIGO DE ATENDIMENTO, NOME DO PACIENTE, NOME DO
--------CONVêNIO E SOMENTE DOS ATENDIMENTOS DO 02/05/2016.
--------TABELAS: ATENDIME, PACIENTE E CONVENIO.

            SELECT ATENDIME.CD_ATENDIMENTO
                  ,PACIENTE.NM_PACIENTE
                  ,ATENDIME.DT_ATENDIMENTO
                  ,ATENDIME.DT_ALTA
                  ,CONVENIO.NM_CONVENIO
            FROM ATENDIME ,PACIENTE , CONVENIO

            WHERE ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
            AND    ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
            AND ATENDIME.DT_ATENDIMENTO = TO_DATE ('02/05/2016', 'DD/MM/YYYY')



--------3) CRIAR UMA PESQUISA QUE INFORME O NOME DO PACIENTE, O CóDIGO DO PACIENTE, O NOME DA CIDADE DA CIDADE
--------EM QUE O PACIENTE RESIDE, E O CóDIGO DE ATENDIMENTO DO PACIENTE.

            SELECT PACIENTE.NM_PACIENTE
                  ,PACIENTE.CD_PACIENTE
                  ,CIDADE.NM_CIDADE
                  ,ATENDIME.CD_ATENDIMENTO
            FROM ATENDIME , PACIENTE,CIDADE
            WHERE ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
            AND   CIDADE.CD_CIDADE = PACIENTE.CD_CIDADE

--------TABELAS: ATENDIME, CIDADE E PACIENTE.
--------4) FAZER UM SELECT DOS PACIENTES INTERNADOS DURANTE O MêS DE AGOSTO DE 2016, COM IDADE
--------MAIOR OU IGUAL A 50 ANOS. DICA: O RESULTADO TERá 20 RETORNOS (LINHAS).

              SELECT  PACIENTE.CD_PACIENTE
                    ,PACIENTE.NM_PACIENTE
                    , TRUNC((SYSDATE - PACIENTE.DT_NASCIMENTO)/365) AS IDADE
                    , ATENDIME.TP_ATENDIMENTO
              FROM  PACIENTE, ATENDIME
              WHERE  idade>=50
              AND  ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
              AND ATENDIME.TP_ATENDIMENTO = 'I' --||'NTERNADOS'
              AND ATENDIME.DT_ATENDIMENTO BETWEEN TO_DATE('01/08/2016','DD/MM/YYYY')
                                              AND TO_DATE('31/08/2016','DD/MM/YYYY')

--------5) TOTAL DE ATENDIMENTO DO MêS DE JANEIRO DE 2018, SEPARADOS POR TIPO DE ATENDIMENTO.

                SELECT COUNT (ATENDIME.TP_ATENDIMENTO),
                       ATENDIME.TP_ATENDIMENTO  ,
                       ATENDIME.DT_ATENDIMENTO
                FROM ATENDIME
                WHERE  ATENDIME.DT_ATENDIMENTO BETWEEN TO_DATE('01/01/2018','DD/MM/YYYY')
                                                   AND TO_DATE('31/01/2018','DD/MM/YYYY')
                GROUP BY ATENDIME.TP_ATENDIMENTO , ATENDIME.DT_ATENDIMENTO


--------6) PRESTADOR COM MAIS CIRURGIAS EM 2017.
--------TABELAS: ATENDIME, AVISO_CIRURGIA E PRESTADOR.
          SELECT * FROM(
          SELECT  COUNT (PRESTADOR.CD_PRESTADOR) QTD_CIRUGIAS, PRESTADOR.NM_PRESTADOR
          FROM  ATENDIME , AVISO_CIRURGIA , PRESTADOR
          WHERE  AVISO_CIRURGIA.DT_REALIZACAO BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY')
                                                  AND TO_DATE('31/12/2017','DD/MM/YYYY')
          AND   ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
          AND   ATENDIME.CD_PACIENTE  =  AVISO_CIRURGIA.CD_PACIENTE
       --
          GROUP BY PRESTADOR.CD_PRESTADOR , PRESTADOR.NM_PRESTADOR
          ORDER BY QTD_CIRUGIAS DESC)
          WHERE    ROWNUM  <= 1



--------7) RETORNAR AS 10 CIRURGIAS MAIS REALIZADAS EM 2017.

              SELECT *
              FROM (
              SELECT  COUNT(CIRURGIA.CD_CIRURGIA)AS QTD,
                             CIRURGIA.DS_CIRURGIA
              FROM AVISO_CIRURGIA,CIRURGIA_AVISO,CIRURGIA
              WHERE CIRURGIA_AVISO.CD_AVISO_CIRURGIA = AVISO_CIRURGIA.CD_AVISO_CIRURGIA
              AND  CIRURGIA.CD_CIRURGIA =  CIRURGIA_AVISO.CD_CIRURGIA
              AND  AVISO_CIRURGIA.DT_REALIZACAO BETWEEN TO_DATE('01/01/2017','DD/MM/YYYY')
                                                  AND TO_DATE('31/12/2017','DD/MM/YYYY')

              GROUP BY CIRURGIA.CD_CIRURGIA, CIRURGIA.DS_CIRURGIA
              ORDER BY QTD DESC
              )
              WHERE ROWNUM  <= 10



--------8) UM SELECT TRAGA A IDADE DO PACIENTE UTILIZANDO O COMANDO SYSDATE E DATA DE
--------NASCIMENTO, ANEXANDO NA PESQUISA A CID ( CLASSIFICAçãO INTERNACIONAL DE DOENçAS ) ,
--------PARA INFORMAR A DESCRIçãO DA DOENçA QUE FOI INDICADA NO ATENDIMENTO DO PACIENTE.

               SELECT TRUNC((SYSDATE - PACIENTE.DT_NASCIMENTO)/365) AS IDADE
                      , PACIENTE.NM_PACIENTE
                      , CID.CD_CID
                      , CID.DS_CID
               FROM ATENDIME,PACIENTE ,CID
               WHERE ATENDIME.CD_CID = CID.CD_CID
               AND  ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
        ---       AND TRUNC((SYSDATE - PACIENTE.DT_NASCIMENTO)/365) AS IDADE IS NOT NULL
               ORDER BY IDADE DESC ;

--------9) CRIAR UMA PESQUISA PARA ATENDIMENTOS DE CóDIGO MAIOR QUE 5000 CUJO O CóDIGO DO
--------PRESTADOR DO ATENDIMENTO SEJA 407, 1562, 3071. DICA: UTILIZAR O RELACIONAL IN.

                SELECT PRESTADOR.NM_PRESTADOR
                       ,  ATENDIME.CD_ATENDIMENTO
                FROM  PRESTADOR,ATENDIME
                WHERE PRESTADOR.CD_PRESTADOR IN (407, 1562, 3071)
                AND   ATENDIME.CD_ATENDIMENTO >5000
                AND   ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
               -- GROUP BY PRESTADOR.NM_PRESTADOR  ,ATENDIME.CD_ATENDIMENTO

--------10) FAZER UM SELECT COM TODOS OS ATENDIMENTOS REALIZADOS POR PRESTADORES DO ESTADO DO RIO DE JANEIRO.

                SELECT COUNT(PRESTADOR.CD_PRESTADOR)
                      --COUNT(ATENDIME.CD_ATENDIMENTO)
                          --  ATENDIME.CD_ATENDIMENTO
                            ,PRESTADOR.CD_PRESTADOR
                            ,PRESTADOR.NM_PRESTADOR
                FROM   PRESTADOR, ATENDIME
                WHERE PRESTADOR.CD_UF_ORGAO_EMISSOR ='RJ'
                AND ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
                GROUP BY ATENDIME.CD_ATENDIMENTO, PRESTADOR.CD_PRESTADOR,PRESTADOR.NM_PRESTADOR


--------PARTE 2:
--------1) FAZER UM SELECT COM O SOMATóRIO DE PRESTADORES POR ESTADO DE RESIDENCIA. DICA: UTILIZAR SUM() E GROUP
--------BY.
              SELECT SUM (PRESTADOR.CD_PRESTADOR),
                          PRESTADOR.CD_UF_ORGAO_EMISSOR
              FROM   PRESTADOR
              GROUP BY PRESTADOR.CD_UF_ORGAO_EMISSOR

--------2) FAZER UM SELECT COM CóDIGO DE TODOS OS ITENS DA CONTA DE INTERNAçãO, NOME DO
--------PACIENTE E NOME DO PROCEDIMENTO. TABELAS: ITREG_FAT, PRO_FAT, PACIENTE.

              SELECT PACIENTE.NM_PACIENTE ,ITREG_FAT.CD_REG_FAT, PRO_FAT.DS_PRO_FAT
              FROM  ITREG_FAT , PRO_FAT, PACIENTE ,ATENDIME
              WHERE  PRO_FAT.CD_PRO_FAT = ITREG_FAT.CD_PRO_FAT
              AND    ATENDIME.CD_PRESTADOR = ITREG_FAT.CD_PRESTADOR
              AND    ATENDIME.CD_PACIENTE  = PACIENTE.CD_PACIENTE
              AND    ATENDIME.TP_ATENDIMENTO = 'I'

--------3) FAZER UM SELECT COM TODOS OS CóDIGOS DAS CONTAS COM MAIS DE R$1000,00 NO MêS DE
--------SETEMBRO DE 2017. TRAZER CóDIGOS DA CONTA E VALOR, ORDENADOS POR VALOR DECRESCENTE.

--------4) QUANTIDADE DE PACIENTES ATENDIDOS NO ANO DE 2016.

                SELECT  Count (atendime.cd_paciente) qtd
                FROM  atendime, paciente
                WHERE atendime.cd_paciente = paciente.cd_paciente
                AND   atendime.dt_atendimento BETWEEN To_Date('01/01/2016','dd/mm/yyyy')
                                                  AND To_Date('31/12/2016','dd/mm/yyyy')



--------5) FAZER UM SELECT COM O SOMATóRIO DE FATURAMENTO EM INTERNAÇÃO POR PRESTADOR NO ANO
--------DE 2018. DICA: AGRUPAR PELO PRESTADOR O SOMATóRIO DE VALORES UNITáRIOS.

--------6) FAZER UM SELECT COM A QUANTIDADE DO EXAME CULTURA PARA FUNGOS NO ANO DE 2017,
--------AGRUPADAS POR PRESTADOR. DICA: UTILIZAR A ITREG_FAT, PRO_FAT (TABELA DOS PROCEDIMENTOS) E PRESTADOR.
              SELECT COUNT (PRO_FAT.CD_PRO_FAT) QTD
                            ,PRESTADOR.CD_PRESTADOR
                            ,PRESTADOR.NM_PRESTADOR

              FROM ITREG_FAT, PRO_FAT ,PRESTADOR ---4310140

              WHERE PRO_FAT.CD_PRO_FAT = ITREG_FAT.CD_PRO_FAT
              AND ITREG_FAT.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
              AND PRO_FAT.DS_UNIDADE = 'EXAME'
              AND PRO_FAT.CD_PRO_FAT = '40310140'
              AND ITREG_FAT.DT_LANCAMENTO BETWEEN TO_DATE ('01/01/2017','DD/MM/YYYY')
                                              AND TO_DATE ('31/12/2017','DD/MM/YYYY')
              GROUP BY PRO_FAT.CD_PRO_FAT
                      ,PRESTADOR.CD_PRESTADOR
                      ,PRESTADOR.NM_PRESTADOR
--------PARTE 3:
--------1) TRAZER NUMA LINHA Só O PACIENTE COM MAIS ATENDIMENTO EM 2018, COM O CóDIGO, NOME DO PACIENTE E
--------CONVêNIO. DICA: FAZER UM CONTADOR PARA O NúMERO DE ATENDIMENTOS.

                  SELECT * FROM
                  (
                  SELECT COUNT (ATENDIME.CD_ATENDIMENTO)AS QTD,
                                PACIENTE.NM_PACIENTE,
                                CONVENIO.NM_CONVENIO
                  FROM  ATENDIME , PACIENTE , CONVENIO
                  WHERE  ATENDIME.DT_ATENDIMENTO BETWEEN TO_DATE('01/01/2018','DD/MM/YYYY')
                                                     AND TO_DATE('31/12/2018','DD/MM/YYYY')
                  AND   ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
                  AND   ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
                  GROUP BY  PACIENTE.CD_PACIENTE ,PACIENTE.NM_PACIENTE,CONVENIO.NM_CONVENIO
                  ORDER BY  QTD DESC
                  )
                  WHERE ROWNUM <=1



--------2) FAZER UM SELECT COM TODAS CONTA DA ITREG_FAT, NOME DO PACIENTE, NOME DO PRESTADOR, NOME DO
--------CONVENIO, NOME DO PROCEDIMENTO, VALOR DO PROCEDIMENTO (VL_CONTA_TOTAL) DOS 3 PRIMEIROS MESES DE
--------2017.
                     SELECT   ITREG_FAT.CD_REG_FAT,
                              PACIENTE.NM_PACIENTE,
                              PRESTADOR.NM_PRESTADOR,
                              CONVENIO.NM_CONVENIO,
                              PRO_FAT.DS_PRO_FAT,
                              ITREG_FAT.VL_TOTAL_CONTA

                     FROM  ITREG_FAT, PACIENTE, PRESTADOR , ATENDIME,CONVENIO,PRO_FAT
                     WHERE   ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
                     AND     ITREG_FAT.CD_PRO_FAT = PRO_FAT.CD_PRO_FAT
                     AND     ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
                     AND     ITREG_FAT.CD_PRESTADOR = PRESTADOR .CD_PRESTADOR
                     AND     ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
                     AND     ITREG_FAT.DT_LANCAMENTO BETWEEN To_Date ('01/01/2017','DD/MM/YYYY')
                                                         AND To_Date ('31/03/2017','DD/MM/YYYY')
                     ORDER BY  ITREG_FAT.DT_LANCAMENTO



--------3) FAZER UM SELECT IGUAL AO ANTERIOR, MAS AGORA PARA AS CONTAS AMBULATORIAIS, QUE ULTILIZAM A REG_AMB E
--------ITREG_AMB.        SELECT   ITREG_FAT.CD_REG_FAT,

                       SELECT ITREG_AMB.CD_REG_AMB,
                              PACIENTE.NM_PACIENTE,
                              PRESTADOR.NM_PRESTADOR,
                              CONVENIO.NM_CONVENIO,
                              ITREG_AMB.VL_TOTAL_CONTA

                     FROM  ITREG_AMB, PACIENTE, PRESTADOR , ATENDIME,CONVENIO,REG_AMB
                     WHERE   ATENDIME.CD_PACIENTE = PACIENTE.CD_PACIENTE
                     AND    ITREG_AMB.CD_REG_AMB = REG_AMB.CD_REG_AMB
                     AND     ATENDIME.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
                     AND     ITREG_AMB.CD_PRESTADOR = PRESTADOR.CD_PRESTADOR
                     AND     ATENDIME.CD_CONVENIO = CONVENIO.CD_CONVENIO
                     AND     ITREG_AMB.DT_LANCAMENTO BETWEEN TO_DATE ('01/01/2016','DD/MM/YYYY')
                                                         AND TO_DATE ('31/03/2016','DD/MM/YYYY')
                     ORDER BY  ITREG_AMB.DT_LANCAMENTO



--------PARTE 4:
--------1) TRAZER OS ITENS DAS CONTAS AMBULATORIAIS E DE INTERNAçãO FECHADAS, COM NOME DO
--------CONVENIO, NOME DO PACIENTE E VALOR UNITáRIO E VALOR TOTAL. DICA: UTILIZAR A COLUNA SN_FECHADA DA REG_AMB
--------E REG_FAT.



--------2) IDEM, MAS AGORA TRAZER UM SOMATóRIO POR CONVêNIO.

--------3) MéDIA DO TEMPO DE INTERNAçãO (PACIENTE QUE TIVERAM INTERNAçãO, TEMPO ENTRE ENTRADA E ALTA) POR FAIXA
--------ETáRIA (0 A 10, 11 A 18, 19 A 30, 30 A 45, 46 A 60, 60 A 80 E MAIOR QUE 81).