PROMPT CREATE OR REPLACE PROCEDURE prc_cuboi2_a2_felipe_neves
CREATE OR REPLACE PROCEDURE prc_cuboi2_a2_felipe_neves (P_CD_TAB_FAT  NUMBER,
                                                       P_DT_VIGENCIA DATE)
IS
  CURSOR C_PACIENTE IS
    SELECT *
    FROM  VAL_PRO_CUBOI2_FELIPE_NEVES
    WHERE  CD_TAB_FAT = P_CD_TAB_FAT
           AND DT_VIGENCIA > P_DT_VIGENCIA;
  V_DADOS C_PACIENTE%ROWTYPE;
BEGIN
    DELETE VAL_PRO_CUBOI2_FELIPE_NEVES
    WHERE  CD_TAB_FAT = P_CD_TAB_FAT
           AND DT_VIGENCIA <= P_DT_VIGENCIA;

    OPEN C_PACIENTE;

    FETCH C_PACIENTE INTO V_DADOS;

    UPDATE VAL_PRO_CUBOI2_FELIPE_NEVES
    SET    VL_TOTAL = ( VL_TOTAL * 15 ) / 100
    WHERE  CD_TAB_FAT IN( 43, 51 )
           AND CD_TAB_FAT = P_CD_TAB_FAT;

    UPDATE VAL_PRO_CUBOI2_FELIPE_NEVES
    SET    VL_TOTAL = ( VL_TOTAL * 5 ) / 100
    WHERE  CD_TAB_FAT NOT IN ( 43, 51 )
           AND CD_TAB_FAT = P_CD_TAB_FAT;

    CLOSE C_PACIENTE;
END;
/

